services:

  db:
    container_name: admin-mysql_db
    image: mysql:5.7.41
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BE_197933
      MYSQL_USER: admin
      MYSQL_PASSWORD: admins
    networks:
      - prestashop_network
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./prestashop.sql:/docker-entrypoint-initdb.d/prestashop.sql

  prestashop:
    container_name: prestashop
    build: .
    restart: unless-stopped
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=db
      - DB_NAME=BE_197933
      - DB_USER=admin
      - DB_PASSWD=admins
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=0
      - PS_ADMIN_EMAIL=jaku6p@gmail.com
      - PS_ADMIN_PASSWORD=12345678
    volumes:
      - ps_data:/var/www/html
      - ps_cache:/var/www/html/var/cache
    networks:
      - prestashop_network
      
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  dbdata:
  ps_data:
  ps_cache:
  caddy_data:
  caddy_config: