services:
  prestashop:
    image: x0j3m/be_197933_pancernik
    container_name: BE_197933_prestashop
    restart: unless-stopped
    ports:
      #- "80:80"
      - "19793:443"
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=admin-mysql_db
      - DB_NAME=BE_197933
      - DB_USER=root
      - DB_PASSWD=student
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=0
      - PS_ADMIN_EMAIL=jaku6p@gmail.com
      - PS_ADMIN_PASSWORD=12345678
    #volumes:
    #  - ./img_prod:/var/www/html
    networks:
      - prestashop_network
      - admin-mysql_default
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - prestashop_network
      - admin-mysql_default

networks:
  prestashop_network:
  admin-mysql_default:
    external: true