<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWmp5tyg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWmp5tyg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWmp5tyg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWmp5tyg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWmp5tyg\appDevDebugProjectContainer([
    'container.build_hash' => 'Wmp5tyg',
    'container.build_id' => '1620c38e',
    'container.build_time' => 1762278520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWmp5tyg');
