<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmv7ix1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmv7ix1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXmv7ix1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXmv7ix1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXmv7ix1\appDevDebugProjectContainer([
    'container.build_hash' => 'Xmv7ix1',
    'container.build_id' => '06d1aead',
    'container.build_time' => 1762277635,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmv7ix1');
