<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGayjhxc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGayjhxc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGayjhxc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGayjhxc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGayjhxc\appDevDebugProjectContainer([
    'container.build_hash' => 'Gayjhxc',
    'container.build_id' => '6c575407',
    'container.build_time' => 1762263467,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGayjhxc');
