<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTx3qydh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTx3qydh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTx3qydh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTx3qydh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTx3qydh\appProdProjectContainer([
    'container.build_hash' => 'Tx3qydh',
    'container.build_id' => '7afc7386',
    'container.build_time' => 1762258846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTx3qydh');
