<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhteuna\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhteuna/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRhteuna.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRhteuna\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRhteuna\appProdProjectContainer([
    'container.build_hash' => 'Rhteuna',
    'container.build_id' => '975bdc06',
    'container.build_time' => 1762858125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhteuna');
