<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPuoysxt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPuoysxt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPuoysxt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPuoysxt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPuoysxt\appProdProjectContainer([
    'container.build_hash' => 'Puoysxt',
    'container.build_id' => '75f774ec',
    'container.build_time' => 1762857507,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPuoysxt');
